### ISSUE TITLE
GIFs using palette can not be loaded

### ISSUE THREAD

**Issue by BeatWolf** [jungomi/lavd#2]
GIF images such as the following one generate an error:

![label](https://user-images.githubusercontent.com/7080953/74085757-c3d2e580-4a7c-11ea-9417-b0920b8f1aa1.gif)

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()

  File "/data1/home/beat.wolf/.local/lib/python3.7/site-packages/watchdog/observers/api.py", line 196, in run
    self.dispatch_events(self.event_queue, self.timeout)

  File "/data1/home/beat.wolf/.local/lib/python3.7/site-packages/watchdog/observers/api.py", line 369, in disp
atch_events
    handler.dispatch(event)

  File "/data1/home/beat.wolf/.local/lib/python3.7/site-packages/watchdog/events.py", line 338, in dispatch
    _method_map[event_type](event)

  File "/data1/home/beat.wolf/.local/lib/python3.7/site-packages/lavd/fs.py", line 361, in on_modified
    self.update_file(event.src_path)

  File "/data1/home/beat.wolf/.local/lib/python3.7/site-packages/lavd/fs.py", line 268, in update_file
    root=self.log_dir,
  File "/data1/home/beat.wolf/.local/lib/python3.7/site-packages/lavd/fs.py", line 115, in insert_file
    image = prepare_image(abs_path, root=root)

  File "/data1/home/beat.wolf/.local/lib/python3.7/site-packages/lavd/fs.py", line 67, in prepare_image
    image.save(buffer, "jpeg")

  File "/data1/home/beat.wolf/.local/lib/python3.7/site-packages/PIL/Image.py", line 2088, in save
    save_handler(self, fp, filename)
  File "/data1/home/beat.wolf/.local/lib/python3.7/site-packages/PIL/JpegImagePlugin.py", line 630, in _save

    raise IOError("cannot write mode %s as JPEG" % im.mode)

OSError: cannot write mode P as JPEG`

The easiest fix might be to convert the image to RGB before creating a thumbnail in prepare_image:
`image.convert('RGB').save(buffer, "jpeg")`
```

**Comment by jungomi** [comment]
That was already fixed in 59c03b9746372186483eed883a1a9575eeed6f6b. It's just not in 0.1.1

![lad-example](https://user-images.githubusercontent.com/3986846/74085892-15c83b00-4a7e-11ea-827d-414832c41781.gif)
